### ISSUE TITLE
Quick Jump List broken in Windows 10

### ISSUE THREAD

**Issue by kenosando** [FauxFaux/PuTTYTray#205]
I am running the final, shipped version of Windows 10 and didn't think to test this on my VM running the Tech Preview - quick jump lists do not open for the Putty icon pinned to the task bar. All the pinned/recent connections show up, and you can pin/unpin said connections, but clicking on any of the connections in the list just opens the main putty config window.

**Comment by Pauligrinder** [comment]
I have the same issue. Until build 10130 the whole menu didn't even apear, and since then it just hasn't worked.

**Comment by carukc** [comment]
Same here... I hope that they are able to fix.  I use PuttyTray all the time.

**Comment by Berzerker** [comment]
Yup, broken for me as well. Latest release build.

**Comment by pokmot** [comment]
Same here.

**Comment by voltagex** [comment]
I've attempted to debug this issue but it's tricky as Windows 10 isn't allowing VS2015 to set a JIT debugger for all of Windows (so DebugBreak isn't working).

It doesn't look like PuTTY is getting any command line from the JumpList items. Can someone on Windows 8 please tell me what cmdline is set to when you click on a JumpList item?

**Comment by kohenkatz** [comment]
This is a known issue in PuTTY, fixed in the current snapshots.

See http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/win10-jumplists.html

**Comment by voltagex** [comment]
Interesting. I wonder if that should go to Microsoft as a bug report, too
(to where though?)

**Comment by blindpet** [comment]
@kohenkatz I am running Putty snapshot 2015-8-26.54dcfb0 and jumplists still don't work

**Comment by kohenkatz** [comment]
@blindpet You need to open each connection once from the PuTTY window in order to "re-register" it in the jump list.

**Comment by blindpet** [comment]
@kohenkatz thank you!

**Comment by FauxFaux** [comment]
Thanks @kohenkatz , that fix works for me too, so I've cherry-picked it back (4bf1fe35a5ee7050a14f0640e296e69e7e91394d); will be in the next release.

Shame about the re-registering thing, but I'm guessing people will get it fixed for themselves pretty quickly.

**Comment by hpawe01** [comment]
@kohenkatz Thanks for the advice. Works for me as well

**Comment by ni-hao-1** [comment]
I have beta v0.66 installed at windows 10. The jump list is working again but the list is a lot smaller than I had at my previous windows release. Seems that there is a lower maximum of allowed items....
